-- +goose Up

-- Extended plugin metadata (WebhookPlugin spec)
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS namespace TEXT NOT NULL DEFAULT '';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS icon TEXT NOT NULL DEFAULT '';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS license TEXT NOT NULL DEFAULT '';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS homepage TEXT NOT NULL DEFAULT '';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS match_types TEXT NOT NULL DEFAULT '*';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS connect_domains TEXT NOT NULL DEFAULT '*';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS grant_perms TEXT NOT NULL DEFAULT '';
