import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// Release signing. Two sources, tried in order:
//   1) GitHub Actions: a keystore decoded from the base64 secret SIGNING_KEY into
//      $SIGNING_STORE_FILE, with alias / passwords in SIGNING_KEY_ALIAS /
//      SIGNING_KEY_PASSWORD / SIGNING_STORE_PASSWORD. The CI workflow decodes the
//      secret and exports these before assembling the release.
//   2) Local dev: a .properties file at JEV_KEYSTORE_PROPS (default
//      H:/android/keys/jev-release.properties).
// If neither is present, release builds stay UNSIGNED (so CI without the secret
// still compiles and the debug APK remains installable).
val signStoreFile = System.getenv("SIGNING_STORE_FILE")?.takeIf { File(it).exists() }
val signAlias = System.getenv("SIGNING_KEY_ALIAS")
val signKeyPass = System.getenv("SIGNING_KEY_PASSWORD")
val signStorePass = System.getenv("SIGNING_STORE_PASSWORD")

val releaseProps = Properties().apply {
    // File(...) instead of file(...): the Kotlin DSL file() helper treats the
    // "H:" prefix as a URL scheme and throws on hosts where the env var is
    // unset (e.g. CI). File(...) just yields a non-existent path here, which
    // the exists() guard below handles by leaving release builds unsigned.
    val f = File(System.getenv("JEV_KEYSTORE_PROPS") ?: "H:/android/keys/jev-release.properties")
    if (f.exists()) FileInputStream(f).use { load(it) }
}

android {
    namespace = "com.jev.probe"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.jev.probe"
        minSdk = 30
        targetSdk = 35
        versionCode = 5
        versionName = "1.4"

        // ML Kit's bundled Chinese recognizer ships native libs for every ABI.
        // The target phone (and every phone this can run on: minSdk 30) is
        // arm64, so keep only that one — the other three are dead weight.
        ndk {
            abiFilters += listOf("arm64-v8a")
        }
    }

    signingConfigs {
        if (signStoreFile != null && !signAlias.isNullOrBlank()
            && !signKeyPass.isNullOrBlank() && !signStorePass.isNullOrBlank()) {
            create("release") {
                storeFile = file(signStoreFile)
                storePassword = signStorePass
                keyAlias = signAlias
                keyPassword = signKeyPass
                // PKCS12 generated by openssl; pin the type so AGP does not
                // mis-detect the store format and reject the password.
                storeType = "PKCS12"
                // Sign with every scheme: v1 (META-INF/*.RSA, trivially
                // verifiable) + v2 + v3 (modern Android). If this config is
                // applied the APK is signed; the CI verify step enforces that.
                enableV1Signing = true
                enableV2Signing = true
                enableV3Signing = true
            }
        } else if (releaseProps.isNotEmpty()) {
            create("release") {
                storeFile = file(releaseProps.getProperty("storeFile"))
                storePassword = releaseProps.getProperty("storePassword")
                keyAlias = releaseProps.getProperty("keyAlias")
                keyPassword = releaseProps.getProperty("keyPassword")
                enableV1Signing = true
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = signingConfigs.findByName("release")
        }
    }

    // Uncompressed, page-aligned .so files: required for the 16 KB page-size
    // devices Android 15+ ships, and it lets the loader mmap the ML Kit natives
    // instead of unpacking them at install time.
    packaging {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    testImplementation("junit:junit:4.13.2")
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    // On-device OCR. The *bundled* Chinese model (not the play-services variant):
    // it works on phones with no Google Play services and needs no model download.
    implementation("com.google.mlkit:text-recognition-chinese:16.0.1")
}
