export { SERVER_NAME, SERVER_VERSION, resolveConfig, HELP_TEXT } from './config.js'
export { createApp } from './app.js'
export { createPluginMcpServer } from './mcp/server.js'
export { classifyPlugin, installSpecFor, parseRepoSpec } from './plugin/classify.js'
export { bridgedToolName } from './plugin/names.js'
export { PluginCatalog, filterRepos } from './github/catalog.js'
export { GithubClient } from './github/client.js'
export { apply, name, inject, resolvePluginConfig } from './dsh-plugin.js'
export type { AppConfig } from './config.js'
export type { PluginKind, GithubRepo, PluginInspection } from './types.js'
